const IconPathVariable = {
    Back  : require('../../assets/icon/left-arrow.png'), 
    Profile  : require('../../assets/icon/user1.png'), 
    Next  : require('../../assets/icon/right-arrow.png'),   
    Menu  : require('../../assets/icon/list.png'),   
    Home  : require('../../assets/icon/home.png'),   
    Course  : require('../../assets/icon/education.png'),   
    College  : require('../../assets/icon/college.png'),   
    User  : require('../../assets/icon/user.png'),   
    Arrow  : require('../../assets/icon/arrow.png'),   
    Up  : require('../../assets/icon/up.png'),   
    Left  : require('../../assets/icon/left.png'),   
    Down  : require('../../assets/icon/down.png'),   
    Dot  : require('../../assets/icon/dot.png'),   
    Location  : require('../../assets/icon/pin.png'),   
    Search  : require('../../assets/icon/search.png'),   
    Search1  : require('../../assets/icon/loupe.png'),   
    Download  : require('../../assets/icon/download.png'),   
    Menu  : require('../../assets/icon/menus.png'),   
    Filter  : require('../../assets/icon/filter.png'),   
    Notification  : require('../../assets/icon/notification.png'),   
    Book  : require('../../assets/icon/open-book.png'),   
    Lock  : require('../../assets/icon/open-lock.png'),   
    Star  : require('../../assets/icon/star.png'),
    Edit  : require('../../assets/icon/edit.png'),      
    Logout  : require('../../assets/icon/logout.png'),   
    Fullstar : require('../../assets/icon/staar.png'),
    Halfstar : require('../../assets/icon/halfstar.png'),
    Fullstar1 : require('../../assets/icon/staar1.png'),
    Star1 : require('../../assets/icon/star1.png'),
    Idea : require('../../assets/icon/idea.png'),
    Close : require('../../assets/icon/close.png'),

}

export default IconPathVariable